# Generated by Django 4.0.1 on 2022-01-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.IntegerField(max_length=250)),
                ('razorpay_order_id', models.IntegerField()),
                ('razorpay_signature', models.IntegerField(max_length=250)),
            ],
        ),
    ]
