# Generated by Django 4.0.1 on 2022-01-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='razorpay_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=200)),
                ('razorpay_payment_id', models.CharField(default='', max_length=200)),
                ('razorpay_signature', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
